### ISSUE TITLE
Freezes for a few seconds upon launch

### ISSUE THREAD

**Issue by in4matix** [neuromorph/glass_grid#1] opened 2023-09-26 16:06 UTC
Awesome extension with blur mode enabled. In Ubuntu 22.04 LTS it freezes mouse cursor for a few seconds after launching and then it gradually improves after a few seconds until it works fine. This issue is not present in Ubuntu 23.10 Beta, but I have no intention of switching to Gnome 45 soon as most of the extensions has not been ported to the new ESM. Many I suspect won't bother. In any case I am very happy with Ubuntu 22.04 and I hope Canonical stays with Gnome 42.9 for 22.04 LTS until all issues have been resolved with Gnome 45. IMO they should totally avoid Gnome 43-44 altogether.

**Comment by neuromorph** [comment] 2023-09-26 18:58
Thank you! I am glad you liked it. 
The mouse cursor freeze is unexpected and sounds annoying. I am also on 22.04 LTS and don't face such an issue. However, I see you are on 42.9 likely with LTS 22.04.3 while I am still on 42.5 with LTS 22.04.2. Not updated yet due to some disk issues. I will need to be able to reproduce the issue so I can identify the bug and fix it. I can test it once I am able to update to 42.9, though I can't think of why that would cause this issue. Meanwhile, you could help with some info:
- Does it happen every time you launch glass grid panel or only once
- Please confirm if you are indeed using 22.04.3 with Gnome 42.9
- Is you system particularly low compute power (e.g. an edge device/ single board computer or just very old one etc) 
- Please try to disable all extensions except glass grid (you could do it from within the panel also) and then try if the problem persists. This is to see if there is any conflict with some other extension.
- Can you provide a screen recording maybe to see what's happening?

Thank you for reporting the issue.

**Comment by in4matix** [comment] 2023-09-26 20:34
Thank you for responding. It happens only at first launch, so nothing serious. The only reason I thought of bringing this to your attention is because I am running Ubuntu 23.10 Beta in Boxes on the same machine with only two cores and 4GB of RAM, and I noticed that it is not exhibiting this. I am on 22.04.3 with Gnome 42.9. The screen-cast doesn't really show the issue properly. The screenshot shows the machine specifications. 
[Screencast from 26-09-2023 22:15:33.webm](https://github.com/neuromorph/glass_grid/assets/62904593/3e71866d-849f-4004-b9fd-2b582c9461a9)
![Screenshot from 2023-09-26 22-17-38](https://github.com/neuromorph/glass_grid/assets/62904593/4537baf3-8876-4d23-b679-21af4cb73466)

**Comment by in4matix** [comment] 2023-09-26 22:54
Just an update. I notice that it is also doing it after installing a new app, even more so. I think it is a desktop refresh issue with either Wayland or Mutter in Ubuntu 23.4.3

**Comment by neuromorph** [comment] 2023-09-28 11:18
Thank you for sharing the details. There maybe a component of Wayland/Mutter doing something and I hope they fix it in next updates. However, in the screen-cast I noticed that you have many pages of extensions, which is excellent scenario for using this extension, but it could take some processing to load the extensions details. So, I changed the code to improve the performance and I do hope it will not hang anymore upon launch. 
Can you please try it out and let me know how it goes. I am already using the new code and works well here but I would like to iron out any issue before publishing it.  It is available as GitHub release - https://github.com/neuromorph/glass_grid/releases/download/g42-44/extgrid@neuromorph.zip  

You need to download the release zip file and unzip at this location (delete/overwrite existing folder): `~/.local/share/gnome-shell/extensions/`
You need to restart the gnome shell environment:  
` logout and login again (do this if using Wayland) or  
    alt+f2 then type r and enter (for Xorg)`

**Comment by in4matix** [comment] 2023-09-28 12:58
I can confirm there is now a major improvement. As a matter of fact it seems to be working flawlessly even while running a stress test. Thank you, much appreciated! 

![Screenshot from 2023-09-28 14-46-23](https://github.com/neuromorph/glass_grid/assets/62904593/51c35da5-8fe7-40e0-b5a5-b58f1dfcb8bd)

**Comment by neuromorph** [comment] 2023-09-28 17:16
You are welcome and thanks for the test! I will publish the update for 42-44 first. Later it'll need to be ported to 45.
Marking the issue as resolved but I'll close in a couple days, in case you face any issues you can report here.

**Comment by neuromorph** [comment] 2023-10-01 16:49
Closing the issue now. For Gnome 45 users, the update will be ported to 45 soon.

**Closed as completed by neuromorph** 2023-10-01 16:49 UTC
Labels: enhancement
