### ISSUE TITLE
Panel goes beyond the screen for high display scalings

### ISSUE THREAD

**Issue by FelixFourcolor** [neuromorph/glass_grid#3] opened 2023-11-03 03:31 UTC
Expectation: The glass panel should occupy roughly the same proportion of the screen regardless of scaling.

Reality (Gnome 45.1): I have a 4k monitor, and the panel looks like this for 1x - 4x scaling

1x
![Screenshot from 2023-11-02 19-25-38](https://github.com/neuromorph/glass_grid/assets/34260584/e7c7ff6a-2029-4113-969e-b30f6ad1509c)
2x
![Screenshot from 2023-11-02 19-25-59](https://github.com/neuromorph/glass_grid/assets/34260584/8b80004c-61e8-49dc-8ce4-d873a47e3293)

3x (still readable, but notice that the white border has gone beyond the screen)
![Screenshot from 2023-11-02 19-26-20](https://github.com/neuromorph/glass_grid/assets/34260584/86ed4286-64e3-4494-a386-182add8d220c)
4x (unreadable)
![Screenshot from 2023-11-02 19-26-42](https://github.com/neuromorph/glass_grid/assets/34260584/11de4260-7278-4c63-9721-ac7a5b0b015c)

Actually I'm fine if the panel is small for low scaling, because everything else is also small and the desktop is not intended to be used in that state. But it really shouldn't go beyond the screen for high scaling like 3x and 4x.

**Comment by neuromorph** [comment] 2023-11-05 11:58
> Expectation: The glass panel should occupy roughly the same proportion of the screen regardless of scaling.

This is incorrect. All widgets (if scaling support implemented) will scale with display scale setting and so will not occupy the same proportion of the screen (physically). 

However, you are right that currently it scales boundlessly and can go out of screen which is not desirable. I did not anticipate usage with 3x or 4x scale :). So, are you trying edge cases for test or do you actually use in 3x-4x scale?

Initially, the extension window had dynamic size based on screen size but it wasn't giving uniform layout on screens of different resolutions so I changed it to a fixed size that gets scaled with display scale but stays uniform. I will try to make it dynamic again so it respects the screen size and does not go out. I will update here once I have something ready so you can try it out.

Also, the first icon in the top bar is supposed to be an 'i' in a circle but in pictures it looks like just a white square, not sure why.

Thank you for reporting, FelixFourcolor !

**Comment by FelixFourcolor** [comment] 2023-11-05 12:09
> So, are you trying edge cases for test or do you actually use in 3x-4x scale?

Indeed me trying 4x was just testing for edge case (also for the sake of completeness to report the issue), but 3x feels very natural for 4k displays and is actually the setting I use.

> Also, the first icon in the top bar is supposed to be an 'i' in a circle but in pictures it looks like just a white square, not sure why.

Oh, I never noticed that. I don't mind it anyway.

> I will update here once I have something ready so you can try it out.

Thank you for your work. I really love your extension, I just find it a bit rough around the edges. I hope you don't mind me continuing to report issues as I find them. (If you didn't know I was the one writing a review on EGO complaining about glitches.)

**Comment by FelixFourcolor** [comment] 2023-11-06 06:22
To further the point that I was not merely testing for edge case, this is my laptop with 2x scaling (the setting I actually use). It's not quite as bad as 3x on my 4k monitor, but still not ideal.

![Screenshot from 2023-11-05 22-18-01](https://github.com/neuromorph/glass_grid/assets/34260584/f524d45b-749b-48f9-aaf9-18fb39ab4c64)

**Comment by neuromorph** [comment] 2023-11-06 07:10
> Thank you for your work. I really love your extension, I just find it a bit rough around the edges.

Thank you, appreciate it! Yes, it can be a bit rough around the edges. Since I couldn't leverage an existing Gnome shell component (e.g. the panel menu), things like input handling etc had to be manually implemented along with the UI stuff. In fact, I tried many iterations for the UI (the looks I mean) but wasn't fully satisfied so at some point I just had to wrap it up. It should be functional though.

>  I hope you don't mind me continuing to report issues as I find them.

Yes, please report any issues you may face. Also, if you find any important feature is missing, raise that too. It certainly helps to know what is broken or missing. I will try to fix them as much as possible, besides if someone else comes across the issues they may be able to contribute as well. 

> If you didn't know I was the one writing a review on EGO complaining about glitches.

Oh, good to know. I was wondering about what were the glitches :)

> this is my laptop with 2x scaling (the setting I actually use). It's not quite as bad as 3x on my 4k monitor, but still not ideal.

I see it, will check it out. Also, in this screenshot , the icons look different again, which happens with the theme etc but hope you are still on Gnome 45, since the codebase is different for prior to 45.

Alright, I will get back when I have some update on this scaling issue.

**Comment by FelixFourcolor** [comment] 2023-11-06 07:22
> Also, in this screenshot , the icons look different again, which happens with the theme etc but hope you are still on Gnome 45

It's still Gnome 45, but with a different icon theme.

**Comment by neuromorph** [comment] 2023-11-09 16:03
OK, I have an update. I decided to slow the scaling so it does not grow out of screen. The thing is that even if I control the size of the glass panel, the internal components, mainly icons and fonts, tend to grow with original scaling from Gnome. So, I added individual override to customize the scale of the components as well. It should work for useful scaling ranges, though may have some glitch for extreme scaling. I tested with VM as I don't have 4k screen (nor 45).

Can you please try it out and let me know how it goes. It is available as GitHub release - https://github.com/neuromorph/glass_grid/archive/refs/tags/v13-Gnome45-ScalingFix.zip

You need to download/unzip the release zip file and copy the files and sub-directories to this location (delete/overwrite existing): ~/.local/share/gnome-shell/extensions/extgrid@neuromorph/

You need to restart the gnome shell environment:
 logout and login again (do this if using Wayland) or   alt+f2 then type r and enter (for Xorg)

**Comment by FelixFourcolor** [comment] 2023-11-09 17:09
On my laptop (2x scaling)

Old
![Screenshot from 2023-11-09 08-37-48](https://github.com/neuromorph/glass_grid/assets/34260584/2769b7a1-dc20-4c95-9c65-2c95bcb98fa9)

New
![Screenshot from 2023-11-09 08-42-56](https://github.com/neuromorph/glass_grid/assets/34260584/859b45e4-8ac8-4fb6-8549-85eb831a6d6c)

The border does shrink, but the texts also get blurry. Also they don't seem to get smaller, only the borders around them shrink.

Is there any way to natively scale the texts, something like how gnome-tweaks does it with the font scaling factor? Perhaps it will solve both problems.

(Tested on both X11 and Wayland, same results.)

**Comment by neuromorph** [comment] 2023-11-09 19:04
Hello Felix,
Thank you for checking! 

I have added a fix for the text/font, now it should also scale.  Please replace the local 'extension.js' file with - https://github.com/neuromorph/glass_grid/blob/g45-port/extension.js

Also, there is a font +/- option in settings menu. You may try that as well for finer font adjustments. 

Hope it will fix the issue. Also, let me know the resolution of your laptop screen, so I can try simulating same in VM.

**Comment by FelixFourcolor** [comment] 2023-11-09 23:45
> Also, there is a font +/- option in settings menu.

Apologies, I didn't see it last time. That already fixed the font scaling.

I've tried the latest patch. The text is smaller than last time, but still blurry. Strangely, it gets crisp when you click + or - font size, but reverts to blurry when the mouse loses focus of the settings panel. 

>  Let me know the resolution of your laptop screen

Sorry, should've said it earlier. It's 2560 x 1600. I use 2x display scaling and 0.87x font scaling (in gnome-tweaks).

**Comment by neuromorph** [comment] 2023-11-10 10:00
> The text is smaller than last time, but still blurry. Strangely, it gets crisp when you click + or - font size, but reverts to blurry when the mouse loses focus of the settings panel.

That is weird, especially the on mouse losing focus part :eyes: . It seems to me that the font rendering gets messed up for certain settings of font-size (font-size is what gets specified in the extension). The font-size is increased or decreased fractionally with +/- buttons. Earlier, with display scaling as 2x/3x, the font-size would remain same but Gnome scaling would auto scale its rendering by that factor. Since, I changed the scaling factors for the extension widgets, the widgets scale a bit less. The new patch applies the custom scaling to the font-size so that it scales up less than the display scaling and in alignment with the widget scaling. I believe fonts can have trouble at some combinations of these settings. In this case, I would expect it to render well if you change the font size with +/- buttons in some settings and blur for some other. Please see if that is the case for you i.e. if the problem is resolved by changing font size with +/- for some settings.

Otherwise, I am not sure why that is happening. I will check if I can find something. 

Also, if you do use the +/- for scaling, is it better with the patch or without the new patch? In case the added font scaling isn't really helpful.

> It's 2560 x 1600. I use 2x display scaling and 0.87x font scaling (in gnome-tweaks).

Well, I couldn't simulate it in Gnome Boxes as it does not have this resolution option nor could I install tweaks in the Gnome Nightly image that I am using. But I got the idea of the problem. Cool display btw :+1:

**Comment by FelixFourcolor** [comment] 2023-11-10 11:26
I think you shouldn't worry too about it. The text does get blurrier than before, but not by that much (you can tell by the screenshot).

> Also, if you do use the +/- for scaling, is it better with the patch or without the new patch?

It's hard to say. My laptop looks better with the patch -- before the text was too large; while my 4k monitor looks better before - the patch makes the text too small. Perhaps I would err on the large side, but with the font size setting, I don't think you can go wrong either way.

My 4k monitor looks flawless btw, nothing is blurry. I think the blur is from my display fractional scaling setting (0.87 text scaling on gnome-tweaks) and not something that you can control.

**Comment by neuromorph** [comment] 2023-11-10 16:16
> The text does get blurrier than before, but not by that much (you can tell by the screenshot).

OK, that's good.

> Perhaps I would err on the large side, but with the font size setting, I don't think you can go wrong either way.

Noted, I will plan the update accordingly.

> My 4k monitor looks flawless btw, nothing is blurry. I think the blur is from my display fractional scaling setting (0.87 text scaling on gnome-tweaks) and not something that you can control.

Cool. That makes sense. 

Thank you for testing and providing feedback!

**Closed as completed** 2023-11-14 15:30 UTC
